xmldom/xmldom

t/test

instead of $TRAVIS  to configure test coverage
ref: https://github.com/xmldom/xmldom/issues/3#issuecomment-568730589
this should ~~*hopefully*~~ _definitely_ give us a green Travis CI build ref: #2

[testing] use COVERAGE environment variable

---

package.json

I generally like to have "-dev" package version number on the master branch. This is what we generally do in Apache Cordova. This means that if someone does install from GitHub or tries out a proposal from a PR, it would not show released package version number.
A side point is that I think this should be merged by squash merge (quickest) or perhaps rebase merge, not a merge commit. I would like to avoid merge commits when possible, especially for small single-commit changes.

start xmldom 0.4.0-dev in package.json

---

.github/workflows/test-node.js.yml

from template on GitHub UI
with the following changes:
- update filename
- update name field
- replace `npm ci` with `npm install`
- remove `npm run build` step
This *should* get CI testing working again both on master branch and in PRs
This is in followup to PR #59
/cc @karfau

add test-node.js.yml to GitHub workflows

---

.github/workflows/test-node.js.yml

According to the documentation when the `package-lock.json` is committed to the repo,
`npm ci` is the preferred and reliable way to install dependencies on CI,
since it will not attempt to modify the lock file.
It will also fail in case the dependencies in `package.json`
do not match with the ones in the lock file.
https://docs.npmjs.com/cli/ci

ci(github-actions): Use `npm ci` instead of `npm install`

---

.gitignore

not needed since use of proof was removed by PR #59
/cc @karfau

remove .proof.out from .gitignore

---

.github/workflows/test-node.js.yml

ref: https://docs.npmjs.com/cli/install-ci-test.html
as proposed by @timbru31 in <https://github.com/xmldom/xmldom/pull/68#pullrequestreview-439940271> (PR #68)

single npm cit line in GitHub CI action

---

.github/workflows/stryker.yml
readme.md
stryker.conf.json

as a Node.js action - __updated__
resolves #60
~~/cc @karfau~~

add Stryker action to update dashboard

---

lib/entities.js
test/html/normalize.vows.js

Might be considered a breaking change.
fixes #57

fix: Restore `&nbsp;` behavior from v0.1.27

---

readme.md

- used `prettier-standard --lint` to reformat the example, with semicolons removed, etc., but with 4-space indentation restored (by hand)
- replace `var` with `const`
- use destructured `const` to import the `DOMParser` object
- add blank lines
- move a `console` logging statement
triggered by discussion in issue #75
related to: PR #79 (add note about ES6 import)
✅ **tested** in a new npm package project in my work area
/cc @ajmas

modernize & improve the example in readme.md

---

readme.md

Fixes #75 Add note about import

---

lib/dom.js

The new method getElementsByClassName uses ES6 syntax. This is a problem when trying to polyfill an older engine.

remove ES6 syntax from getElementsByClassName

---

stryker.conf.json

By not running the tests for test/assert.js I think we can reduce the duration of the stryker run.
They shouldn't change the result since they are only test helpers that don't change how the actual code is tested.
Fixes #82

Reduce time needed for stryker

---

.eslintrc.yml
lib/.eslintrc.yml
package-lock.json
package.json

The purpose is to avoid ES6 items that may cause issues with older engines, as discussed in PR #87.
This should guard against newer ES6 syntax that could lead to issues with some ES5 environments such as:
- Jint - https://github.com/sebastienros/jint
- Duktape
- IE11
- Android pre-5.0 WebView (already past EOL)
This PR is based on PR #106.
I would appreciate a quick review from someone, if possible.

use eslint-plugin-es5 to enforce ES5

---

lib/dom-parser.js
test/parse/simple.vows.js

Updates `DOMParser.parseFromString` to also check that the `source` provided is a string. To prevent sax from throwing undefined errors when calling `indexOf` on the source.
Adds unit tests to `test/parse/simple.vows.js` to cover this edge case.
Resolves #98

fix: typecheck source param before parsing

---

CHANGELOG.md

Only referencing #62 for further discussions.

docs: Update CHANGELOG.md through version 0.3.0

---

lib/sax.js
test/parse/node.test.js
test/xmltest/__snapshots__/not-wf.test.js.snap

fix: preserve doctype with sysid (#143)

---

test/dom-parser.test.js
test/parse/parse-element.test.js
test/xss.test.js

test: Use toBe/toStrictEqual instead of toEqual

---

LICENSE
LICENSE.md
package.json
readme.md

As suggested/discussed in the following tickets:
Fixes #172
Fixes #173

Switch to (only) MIT license

---

lib/dom.js
test/dom/serializer.test.js
test/xmltest/__snapshots__/not-wf.test.js.snap

to adhere to the XML specification
https://www.w3.org/TR/xml/#NT-CharData
https://github.com/xmldom/xmldom/issues/58#issuecomment-743231935

fix(dom): Escape `]]>` when serializing CharData

---

readme.md

The URLs to these articles seems to have changed. They are currently pointing to 404 pages.
This Pull Requests updates the links.

Update MDN links in readme.md

---

lib/dom.js
test/html/__snapshots__/normalize.test.js.snap
test/parse/__snapshots__/locator.test.js.snap
test/parse/__snapshots__/simple.test.js.snap
test/xmltest/__snapshots__/not-wf.test.js.snap
test/xmltest/__snapshots__/valid.test.js.snap

to produce well formed XML.
> Well-formedness constraint: No `<` in Attribute Values
> The replacement text of any entity referred to directly or indirectly in an attribute value must not contain a `<`.
https://www.w3.org/TR/xml/#CleanAttrVals
https://www.w3.org/TR/xml/#NT-AttValue
fixes #198

fix: Escape `<` when serializing attribute values

---

renovate.json

As discussed in #212:
> I would favor that we turn these Node.js updates off, as I would consider this kind of an update to be a BREAKING CHANGE. I have not found the documentation how to turn these Node.js updates off.
After this lands I want to verify the configuration by checking the "Retry/rebase" checkbox in #212 and expect that that PR will be auto-closed by renovate.

chore(renovate): Disable for (minimum) node version

---

.github/workflows/stryker.yml

Stryker seems to take 2 hours on GitHub, maybe a little longer with the recent update. I wonder if it may go faster on Node.js 14.

ci: run Stryker on Node.js 14

---

lib/dom.js
test/dom/element.test.js

This seemed to be missing. Without it, xpath (XPath 1.0) works, but
xpath2 (XPath 2.0) and fontoxpath (XPath 3.x) do not match elements.

fix: Set `localName` as part of `Document.createElement`

---

lib/conventions.js
lib/dom-parser.js
lib/dom.js
lib/entities.js
lib/sax.js
test/conventions/__snapshots__/mime-type.test.js.snap
test/conventions/__snapshots__/namespace.test.js.snap
test/conventions/freeze.test.js
test/conventions/mime-type.test.js
test/conventions/namespace.test.js

Before starting to work on fixing #203, where namespaces and mime types are going to be used in multiple places, I decided to gather them in a separate module.
**conventions.js**
- `freeze`: is a small wrapper around `Object.freeze`, that gives type hints
and also "works" if `Object.freeze` should not be available at runtime
- `MIME_TYPE`: has all mime types that are supported by `DOMParser.parseFromString` (second argument)
- `MIME_TYPE.isHTML`: short way to check if a mime type is the only one that enables HTML parsing
- `NAMESPACE`: has all namespaces that we are currently using in the code base
- `NAMESPACE.isHTML`: to check if a given value is the XHTML namespace
**entities.js**
- deprecated `entityMap` (but it's still available as an alias to `HTML_ENTITIES`)
- `HTML_ENTITIES`: new …

refactor: Extract immutable conventions & entities, etc.

---

package-lock.json
package.json

it has been [deprecated and recommends this library](https://gitlab.com/teknopaul/dom-js/-/blob/master/README.md), so I don't think we still need to have it as a devDependency.
(I think it was originally there to compare performance.)

chore(npm): Drop unused devDependency dom-js

---

lib/dom.js
test/dom/serializer.test.js
test/parse/node.test.js

fixes #243 
I moved to tests and the check originally added by @pdecat to a more appropriate place and commented there.
Note: There is no case missing by removing the check for empty prefix in the condition, since
<table>
<tr>
<th>prefix
<th>uri
<th>!prefix && !uri
<th>!uri
<tr>
<td>empty
<td>empty
<td>true
<td>true
<tr>
<td>empty
<td>set
<td>false
<td>false
<tr>
<td>set
<td>empty
<td>false
<td>true
<tr>
<td>set
<td>set
<td>false
<td>false
</table>
so we just additionally cover the missing case

fix: No longer serialize any namespaces with an empty URI

---

lib/conventions.js
lib/dom.js
test/dom/dom-implementation.test.js

- deprecate `hasFeature` and simplify implementation according to the latest spec
- `createDocumentType` sets `publicId` and `systemId` to an empty string instead of `undefined`
- `createDocument` sets `docType` to `null` instead of `undefined`
- export `DocumentType`, `Element`, `Node` and `NodeList` to verify `instanceof` in tests
- update doc comments with links to specs and type information
This PR is part of the preparation for solving #203

feat: Update `DOMImplementation` according to recent specs

---

lib/sax.js
test/parse/parse-element.test.js

by not treating them as part of the tag name.
We drop the additional whitespace as part of parsing.
xmldom was already automatically closing tags that it couldn't find a matching end,
but the whitespace was no longer present.
Strange things started to happen if there were elements after the one with the additional white space.
Fixes #69

fix: Handle whitespace in closing tags

---

lib/dom.js
test/dom/document.test.js

Reimplements `Document.getElementsByClassName` without using a dynamically generated regex.
1. Unlike _CSS grammar_, there seems to be no limitation on which classnames are valid in HTML/DOM (given that they don't contain space chars). That is, `[` seems to be a valid classname, which was broken in this impl as it was fed into a regexp unescaped and caused `xmldom` to throw.
2. Whitespace processing should be now correct. `\s` in JS regexps includes more chars than [space-separated tokens](https://www.w3.org/TR/html52/infrastructure.html#set-of-space-separated-tokens) of html.
3. This now should support a list of space-separated classnames as an argument. Previously, that was broken and order-dependent.
4. This prevents causing a ReDoS by passing in exponential regexps as strings to …

fix(dom): Implement `getElementsByClassName` as specified

---

.npmrc
CHANGELOG.md
package-lock.json
package.json
readme.md

As discussed in the recent days, this PR prepares the scoping of the package into the npm organisation `xmldom` so the new package name is `@xmldom/xmldom`.
See https://docs.npmjs.com/about-scopes
I also checked that the `@` has to be part of the shields/badges URL to work, by looking at https://shields.io/category/version and trying it with an existing scoped package.

chore(npm): Scope package to @xmldom org

---

package.json

since they are visible on github/npm level and don't need to additionally be synced/maintained inside `package.json`, as discussed for followup in PR #278.

chore(package.json): remove author, maintainers, etc.

---

index.d.ts
package.json

This PR partially addresses #191 (see https://github.com/xmldom/xmldom/issues/191#issuecomment-902225494 → step 1). The file was copied from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f378781417e2964083f492ac85bad985d0f47650/types/xmldom/index.d.ts).

fix(types): Copy types from DefinitelyTyped

---

package.json

Sorry, I did not notice earlier. Looks like we will need a 0.7.2 :grimacing:

fix(types): Add index.d.ts to packaged files

---

readme.md
stryker.conf.json

closes #80
I already updated the API key in the github secrets management with the one I received, so landing this PR should trigger the first report to the proper location.

chore(stryker): Switch to dashboard owned by org

---

readme.md

to make it easier to digest.
I recently read some articles on how to structure a README and it became obvious that ours is currently hard to digest.
I think I was able to reorder the headlines so that the most important things for our (potential and existing) users are on the top of the page without a lot of scrolling.
There is still room for improvement, especially regarding splitting some docs into separate markdown files, but that is a slightly bigger topic.
The articles and comments I read:
- https://dev.to/healeycodes/how-to-write-an-awesome-github-readme-2ldc
- https://dev.to/jmfayard/how-to-write-a-good-readme-discuss-4hkl

docs(readme): Improve wording and flow

---

.github/workflows/test-node.js.yml
package-lock.json
package.json

To fix #111 I think it's good enough to split test and lint into two different build steps.
Separate actions are not required since the github actions details view now shows what steps failed.
To be able to do that split, I needed to drop the execution of the `lint` script from the `test` script. The `start` script still runs both in watch mode, so it's still easy to run both when developing.

chore: Split test and lint scripts

---

stryker.conf.json

by pointing it to the existing `test` script instead of the missing `test:jest` srcipt that has been removed in #297

test: Fix stryker config

---

lib/dom-parser.js
lib/index.js
package.json
test/dom-parser.test.js
test/dom/attr.test.js
test/dom/clone.test.js
test/dom/element.test.js
test/dom/fragment.test.js
test/dom/ns-test.test.js
test/dom/serializer.test.js
test/error/error-handler.test.js
test/error/reported-levels.test.js
test/parse/big-file-performance.test.js
test/parse/file.test.js
test/parse/locator.test.js
test/parse/namespace.test.js
test/parse/node.test.js
test/parse/parse-element.test.js
test/xss.test.js

by creating a proper main entry file `lib/index.js`.
NOTE that the following exports have been deprecated in `lib/dom-parser.js` and will be removed in the next minor release:
- `DOMImplementation`
- `XMLSerializer`

refactor: Improve exports & require statements

---

lib/dom-parser.js
test/parse/__snapshots__/test-doc-whitespace.test.js.snap
test/parse/test-doc-whitespace.test.js
test/xmltest/__snapshots__/not-wf.test.js.snap
test/xmltest/__snapshots__/valid.test.js.snap

> XML parsed entities are often stored in computer files which, for editing convenience, are organized into lines. These lines are typically separated by some combination of the characters CARRIAGE RETURN (#xD) and LINE FEED (#xA).
>
> To simplify the tasks of applications, the XML processor must behave as if it normalized all line breaks in external parsed entities (including the document entity) on input, before parsing, by translating both the two-character sequence #xD #xA and any #xD that is not followed by #xA to a single #xA character.
Where `#xD` == `\r` and `#xA` == `\n`, so
` \r\n ` => ` \n `
` \n\r ` => ` \n\n `
` \n  ` => ` \n `
` \r  ` => ` \n `
BREAKING CHANGE: Certain combination of line break characters are normalized before parsing takes place and will no longer be …

fix: Normalize line breaks according to spec

---

lib/dom-parser.js

BREAKING CHANGE: But they are still available from the `@xmldom/xmldom` main package.
closes https://github.com/xmldom/xmldom/issues/53

chore: Drop deprecated exports from `lib/dom-parser.js`

---

lib/sax.js
test/parse/__snapshots__/parse-element.test.js.snap
test/parse/parse-element.test.js

As noted in issue #252 some attributes conflict with prototype fields (such as an attribute `constructor`) thus we must remove the `in` operator and replace with `Object.prototype.hasOwnProperty()`.

fix(sax): Restore ability to parse `__prototype__` attributes

---

.github/workflows/test-node.js.yml

to allow linting to be listed as a separately failing check in the PR.
Really fixes #111
Note: I don't think there is any benefit of splitting them into different files as of now.

ci(github): Split test and lint steps into jobs

---

lib/dom.js
test/dom/serializer.test.js

The regression was introduced as part of #268 by not considering the visible default namespace for attributes without a prefix.
Fixes #319

fix(dom): Preserve default namespace when serializing

---

lib/dom-parser.js
lib/dom.js
lib/sax.js
test/dom/serializer.test.js
test/parse/parse-element.test.js
test/xmltest/__snapshots__/not-wf.test.js.snap
test/xmltest/__snapshots__/valid.test.js.snap

- Added normalization of white space literal characters as specified in https://www.w3.org/TR/xml/#AVNormalize, they now appear as space(s) in the attribute values when accessed from the DOM (and are also serialized as space)
- Added serialization of white space literal values to to the correct numerical character references as described in https://github.com/w3c/DOM-Parsing/issues/59 to fix #284 
BREAKING CHANGE: If you relied on the not spec compliant preservation of `\t`, `\n` or `\r` in **attribute values**. To preserve those you will have to create XML that instead contains the correct numerical (or hexadecimal) equivalent (`&#x9;`, `&#xA;`, `&#xD;`).

fix(XMLSerializer): Preserve whitespace character references

---

.github/workflows/test-node.js.yml

since 16.9.1 was released which fixed the regression in 16.9.0

ci(test): Restore latest node version to 16.x

---

lib/dom.js
test/dom/element.test.js

fix(dom): Remove all links as part of `removeChild`

---

lib/conventions.js
test/conventions/assign.test.js

since we can not rely on it being present in all supported runtimes.
Even though the interface is the same as `Object.assign`,
it behaves slightly differently from the one provided by browsers (see tests).
This was extracted from #338 to support development in #367

feat: Add minimal `Object.assign` ponyfill

---

.github/workflows/examples.yml
examples/nodejs/.gitignore
examples/nodejs/.npmrc
examples/nodejs/package.json
examples/nodejs/src/index.js
examples/typescript-node-es6/.gitignore
examples/typescript-node-es6/.npmrc
examples/typescript-node-es6/package.json
examples/typescript-node-es6/pretest.sh
examples/typescript-node-es6/src/index.ts
examples/typescript-node-es6/tsconfig.json
readme.md

In the context of the threads in #214 I'm have added executable examples and test them as github actions to make sure they don't break.

test: Add executable examples for node and typescript

---

lib/dom.js
test/html/__snapshots__/normalize.test.js.snap
test/xmltest/__snapshots__/not-wf.test.js.snap
test/xmltest/__snapshots__/valid.test.js.snap

in both attributes and text content
Fixes #58
https://w3c.github.io/DOM-Parsing/#xml-serializing-a-text-node
https://w3c.github.io/DOM-Parsing/#serializing-an-element-s-attributes

fix(dom): Serialize `>` as specified

---

readme.md

and (manually) align how those properties are documented
fixes #351

docs: Add `nodeType` values to public interface description

---

examples/typescript-node-es6/src/index.ts
index.d.ts
lib/conventions.js
lib/dom-parser.js
lib/dom.js
lib/entities.js
lib/index.js
lib/sax.js
test/conventions/__snapshots__/html.test.js.snap
test/conventions/__snapshots__/mime-type.test.js.snap
test/conventions/html.test.js
test/dom-parser.test.js
test/dom/document.test.js
test/dom/dom-implementation.test.js
test/dom/element.test.js
test/dom/ns-test.test.js
test/dom/serializer.test.js
test/error/__snapshots__/reported-levels.test.js.snap
test/error/__snapshots__/xml-error.test.js.snap
test/error/reported.js
test/error/xml-reader-dom-handler-errors.test.js
test/get-test-parser.js
test/html/__snapshots__/normalize.test.js.snap
test/html/normalize.test.js
test/xss.test.js

In the living specs for parsing XML and HTML, that this library is trying to implement,
there is a distinction between the different types of documents being parsed:
There are quite some rules that are different for parsing, constructing and serializing XML vs HTML documents.
So far xmldom was always "detecting" whether "the HTML rules should be applied" by looking at the current namespace. So from the first time an the HTML default namespace (`http://www.w3.org/1999/xhtml`) was found, every node was treated as being part of an HTML document. This misconception is the root cause for quite some reported bugs.
BREAKING CHANGE: HTML rules are no longer applied just because of the namespace, but require the `mimeType` argument passed to `DOMParser.parseFromString(source, mimeType)` to match …

fix: Only use HTML rules if mimeType matches

---

lib/dom.js
lib/sax.js

by adding `hasOwnProperty` checks.
https://github.com/xmldom/xmldom/issues/436

fix: Avoid iterating over prototype properties

---

CHANGELOG.md
lib/dom.js
lib/sax.js

This PR backports [the changes from #437](https://github.com/xmldom/xmldom/pull/437/files) to the 0.7.x release, to resolve xmldom/xmldom#436 in older versions. This should address vulnerabilities in [xml-encryption](https://www.npmjs.com/package/xml-encryption) and [xml-crypto](https://www.npmjs.com/package/xml-crypto) (yaronn/xml-crypto#260).
`npm test` passes with the following:

fix: Backport PR-437 to 0.7.x branch

---

lib/sax.js
test/error/__snapshots__/reported-levels.test.js.snap
test/error/reported.js
test/parse/__snapshots__/simple.test.js.snap
test/parse/simple.test.js
test/xmltest/__snapshots__/not-wf.test.js.snap

Previously it was tested as a feature, that tags after incomplete closing tags would be part of the dom. The code responsible for this triggered a CodeQL error suspecting that it could lead to injection of a `script` tag.
BREAKING CHANGE: It no longer reports an error when parsing HTML containing incomplete closing tags, to align the behavior with the one in the browser.
BREAKING CHANGE: If your code relied on not well formed XML to be parsed and include subsequent tags, this will no longer work.
https://github.com/xmldom/xmldom/pull/416

fix: Stop adding tags after incomplete closing tag

---

lib/conventions.js
lib/dom.js
test/conventions/find.test.js

by adding a ponyfill for `Array.prototype.find` to conventions
and converting `let` to `var`

fix: Restore ES5 compatibility

---

lib/dom.js
test/dom/document.test.js

which is slightly different from the checks required when inserting a node.
fixes #455 (only on the master branch for now, I want to test if this also takes care of #456)
https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity https://dom.spec.whatwg.org/#concept-node-replace

fix: Properly check nodes before replacement

---

lib/dom.js
test/dom/element.test.js

BREAKING CHANGE: `Element.getAttribute` and `Element.getAttributeNS` return `null` if the attribute doesn't exist
closes #46
https://dom.spec.whatwg.org/#dom-element-getattribute

fix: `getAttribute` and `getAttributeNS` should return `null`

---

jest.config.js
wallaby.js

the current jest config was causing wallaby to fail, because `testRegex` is supposed to be a string but was a RegExp.
The config for wallaby excludes the test file that is based on stacktrace of errors, since it doesn't work in instrumented files.

chore: Configure jest (correctly) and wallaby

---

test/error/reported-levels.test.js
wallaby.js

instead of completely excluding it.
wallaby output:
jest output:
https://wallabyjs.com/docs/intro/selected-tests.html#test-file-selection

chore: Mark reported-levels.test.js as skipped in wallaby

---

test/parse/__snapshots__/parse-element.test.js.snap
test/parse/parse-element.test.js

and adding snapshots for warnings
The additional output was introduced by the new tests in #485

test: reduce output by using `getTestWrapper` 

---

lib/dom.js
test/dom/dom-comparison.test.js

The PR adds an implementation of level 3 method [`compareDocumentPosition`](https://dom.spec.whatwg.org/#dom-node-comparedocumentposition). This is an updated version of the code suggested in https://github.com/jindw/xmldom/pull/113
The code ran for many years error-free in [Speech Rule Engine](https://github.com/speech-rule-engine/speech-rule-engine) together with  [wicked-good-xpath](https://github.com/google/wicked-good-xpath).

feat: Add compareDocumentPosition method from level 3 spec.

---

lib/dom.js
test/dom/document.test.js

BREAKING CHANGE: Previously it was possible (but not documented) to call `Node.removeChild` with any node in the tree,
and with certain exceptions, it would work. This is no longer the case: calling `Node.removeChild` with an argument that is not a direct child of the node that it is called from, will throw a NotFoundError DOMException, as it is described by the specs.
https://dom.spec.whatwg.org/#concept-node-pre-remove 
Fixes #135

fix: Throw DOMException when calling removeChild with invalid parameter

---

test/error/reported-levels.test.js
test/error/reported.js

@shunkica [told me in #498](https://github.com/xmldom/xmldom/pull/498#issuecomment-1615221065) that `toErrorSnapshot` doesn't work on windows
- cater for windows backslash in file paths
- handle windows backslash before passing it to regular expressions
- convert to unix delimiter before returning the value for OS independent snapshots
- refactor to use understandable variable names for each step

test: make `toErrorSnapshot` windows compatible

---

lib/dom.js
test/dom/processing-instruction.test.js

Add `nodeName` property with tests to ProcessingInstruction

---

.prettierrc.yaml
index.d.ts
lib/conventions.js
lib/dom-parser.js
lib/dom.js
lib/entities.js
lib/grammar.js
lib/sax.js
package-lock.json
package.json
test/dom/document.test.js
test/error/reported-levels.test.js
test/error/reported.js
test/error/xml-reader-dom-handler-errors.test.js
test/get-test-parser.js
test/grammar/utils.js
test/grammar/xml.grammar.js
test/parse/namespace.test.js
test/xmltest/generate-snapshot.js

This PR includes a commit that adds the prettier-plugin-jsdoc dependency to the project.
The plugin will improve the readability and maintainability of our JSDoc comments and ensure a consistent style across the project.

chore: use prettier plugin for jsdoc

---

lib/dom.js
test/dom/node-list.test.js

- `NodeList.item` now checks the `length` attribute before accessing the item at a provided index and returns `null` it the index is out of range
- when updating `LiveNodeList` (as part of accessing the `item` method) and the new `length` is shorter then the current one, any references on indexes following the index starting from `length` are `delete`d, and `null` is returned instead of `undefined`
- added some exports to the `lib/dom.js` module to enable testing
fixes #499

fix(dom): prevent iteration over deleted items

---

.github/workflows/test-node.js.yml

This reverts commit dbd84c6e877897e296b7a570386232deb42b2af7.
It looks like the version that was marked as a prerelease has been removed or untagged.

revert: "chore(deps): update codecov/codecov-action action to v4 (#534)"

---

readme.md

Put install command in distinct block with triple backtick to easily copy/paste in order to save time (dozen seconds or so).

docs: click to copy install command in readme

---

.github/workflows/codeql.yml
.github/workflows/scorecard.yml

Reverts xmldom/xmldom#659
Since the scorecard check failed in the master branch:
https://github.com/xmldom/xmldom/actions/runs/8790973443/job/24124181101

revert: "chore(deps): update github/codeql-action action to v3.25.2"

---

lib/sax.js
test/sax/parseDoctypeInternalSubset.test.js

Added a condition to the parser to allow empty doctypes

fix: parse empty/whitspace only doctype internal subset

---

lib/sax.js
test/sax/parseDoctypeInternalSubset.test.js

with the fix added in #692 `parseDoctypeInternalSubset` has two places that check for the ending symbol and returned the `internalSubSet` as a string. By moving it to the beginning of the while loop, we only need to check the condition once.
I also added tests for more cases ending with a space before the closing square bracket.

refactor: merge redundant ']' condition at start of while loop

---

.github/workflows/examples.yml
.github/workflows/test-node.js.yml
package.json

- drops node versions 10 and 12 from github actions, and add v22
- bumps `engines.node` to >=14
https://github.com/xmldom/xmldom/discussions/495

chore: minimum tested node version is 14

---

index.d.ts

Based on the spec and the current implementation the second argument of DOMParser.parseFromString is not optional and doesn't have a default value.
https://github.com/xmldom/xmldom/blob/9f9a74850a7c929dfd82462e9720a12097bbf426/lib/dom-parser.js#L215
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString
https://html.spec.whatwg.org/#dom-domparser-parsefromstring-dev
This fixes types for changes made in https://github.com/xmldom/xmldom/releases/tag/0.9.0
Previous release https://github.com/xmldom/xmldom/releases/tag/0.8.10 allowed `mimeType` as optional.

fix(types): DOMParser.parseFromString requires mimeType as second argument

---

index.d.ts

fix: correct spelling of `isHTMLMimeType` in type definition

---

examples/typescript-node-es6/src/index.ts
index.d.ts

Adds types for properties that are exported,
but are missing in index.d.ts:
- `Document.domElement`
- `Element.tagName`
Fixes #720

fix: add missing type definitions

---

index.d.ts
lib/dom.js
test/dom/document.test.js
test/dom/element.test.js

the method was previously implemented on the Document interface.
https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByClassName
supersedes #584
fixes #582

feat: add Element.getElementsByClassName

---

examples/typescript-node-es6/src/index.ts
index.d.ts
lib/dom.js

- `Node.nodeType`
- `Node.textContent`
- `Node.columnNumber`
- `Node.lineNumber`
- `ProcessingInstruction.data` (inherited from `CharacterData`)
- `ProcessingInstruction.target`
fixes #725

fix: restore more Node and ProcessingInstruction types

---

examples/typescript-node-es6/src/index.ts
examples/typescript-node-es6/tsconfig.json
index.d.ts

- NodeList and LiveNodeList are now generic, with a default of `Node` when no type argument is passed.
- `Node.getElements*` and `Document.getElements*` return `LiveNodeList<Element>`
- `NodeList[number]` is now typed as `T` instead of `T | undefined`, which of course only works for indexes < `length`
Fixes #731

fix: `getElements*` methods return `LiveNodeList<Element>`

---

examples/typescript-node-es6/src/index.ts
index.d.ts
test/get-test-parser.js

fix(types): correct error handler level to `warning`

---

lib/dom.js
test/dom/node.test.js

as part of https://github.com/xmldom/xmldom/pull/550 ("drop redundant and broken `Element.appendChild` implementation") 
the `_onUpdateChild` was not passed the added child, so the `childNodes` were "re-indexed" from the `firstChild` each time a node was appended. 
This is why the performance degraded significantly, when there are a lot of childNodes to be appended.
fixes https://github.com/xmldom/xmldom/issues/748

fix: restore performance for large amount of child nodes

---

lib/dom-parser.js
test/dom-parser.test.js

Fixed locator not being true by default when using any other options.
Closes #802

fix: locator is now true even when other options are being used for the DOMParser

---

fuzz/__snapshots__/regression.test.js.snap
fuzz/regression.test.js
jest.fuzz.config.js
package-lock.json
package.json

- jazzer [has been deprecated](https://socket.dev/npm/package/@jazzer.js/core/overview/2.1.0) and has tons of deprecated dependencies, and I'm no longer able to install it on my machine, without adding `prebuild` as a devDependency which adds some more deprecated dependencies to the project...
```
npm error code 127
npm error path /home/karfau/dev/xmldom/node_modules/@jazzer.js/fuzzer
npm error command failed
npm error command sh -c prebuild-install --runtime napi || npm run prebuild
npm error > @jazzer.js/fuzzer@2.1.0 prebuild
npm error > prebuild --runtime napi --backend cmake-js --all --strip --verbose
npm error prebuild-install warn This package does not support N-API version undefined
npm error prebuild-install warn install No prebuilt binaries found (target=undefined runtime=napi …
```

chore: drop jazzer and rxjs devDependencies

---

index.d.ts
lib/dom-parser.js
lib/index.js
lib/sax.js
test/dom-parser.test.js
test/parse/normalize-line-endings.test.js
test/parse/parse-element.test.js

Fixes #838, when the default `normalizeLineEndings` implementation is being used

fix: replace \u2029 as part of normalizeLineEndings

---

.github/workflows/codeql.yml
.github/workflows/examples.yml
.github/workflows/test-node.js.yml

Since contributions regularly effect 0.8.x let's use GitHub actions to run the checks.
Following the usual pattern, this is first applied to the master branch, before being ported to the release branch.

ci: execute checks on 0.8.x release branch
