- .travis.yml
- package.json
0.2.0-dev updates with no coveralls and no cache enabled in .travis.ci
> 0.2.0-dev with Travis CI cache disabled

- package.json
- Copyedited description (I also applied this to the repo and org description [I also updated the org icon]).
- Updated maintainers/contributors list.
- Bugs URL updated.
> Various updates to package.json

- t/test
ref:
- https://github.com/xmldom/xmldom/issues/2#issuecomment-568729465
- https://github.com/xmldom/xmldom/issues/3#issuecomment-568730589
nice catch from @timbru31
To be extra safe I think we should first review & merge PR #15 then merge from master to ensure this does not break the build.
> testing: remove extra curl command

- .travis.yml
https://nodejs.org/en/about/releases/
> Run current oldest supported nodejs

- dom.js
Firstly, thank you for writing this lib -- this lib is the only way i could get @azure/storage working within a Service Worker.
This change is adding `Node` to the list of exports
> Added Node to the list of exports

- lib/entities.js
This proposal is triggered by review of PR #84.
It looks like someone added the commented line for testing, looks pretty useless now.
> remove commented line from end of lib/entities.js

- .eslintrc.yml
- package-lock.json
- package.json
mostly extracted from PR #102; one or more upcoming PRs will be based off of this one
~~It is an open question whether this PR should be merged or be superseded by another eslint PR.~~
> add & enable eslint

- jest.config.js
- package-lock.json
- package.json
- test/dom-parser.test.js
as discussed in #72 and #112 so we can get started using jest for new tests.
- `npm run test` run everything there is
- `npm run jest` just runs the jest tests (`test/*.test.js`)
(The tests have been picked from cases that stryker identified in my run in #112 .)
> test: Add jest and first tests

- test/html/normalize.test.js
Fixes a test in `test/html/normalize.test.js` that was ported from Vows to Jest in PR #121
/cc @karfau - can you give this a quick review?
> fix HTML normalize test

- package.json
I would love to get this one into 0.4.0 as well.
> include documents in package files list

- package.json
> chore: Add karfau as contributor

- renovate.json
Fixes #222 
Regression introduced by #221
> chore(renovate): Fix config by removing `$comment` field

- renovate.json
as suggested in recent PRs created by renovate
> chore(renovate): Enable semantic commits

- lib/dom.js
- test/dom/serializer.test.js
> fix: Inherit namespace prefix from parent when required

- package-lock.json
- package.json
Reverts xmldom/xmldom#273
since the checks fail on the master branch.
> Revert "chore(deps): update @stryker-mutator/core -> ^5.3.0 - devdependencies"

- renovate.json
As discussed in https://github.com/xmldom/xmldom/pull/280
https://docs.renovatebot.com/configuration-options/#dependencydashboard
> chore(renovate): Add dependency dashboard

- .npmrc
https://docs.npmjs.com/cli/v6/using-npm/config#tag-version-prefix
> chore(npm): Configure npm to omit version prefix in git tag

- lib/dom.js
> fix: Correct typo in error message

- readme.md
- fix alt text
- use flat-square style (to be consistent with other badges)
in followup to this comment on PR #292: https://github.com/xmldom/xmldom/pull/292/files#r694999142
> docs: fix Stryker badge

- readme.md
TODO:
up to @karfau if you want to go ahead with this or not
> docs: update link to help-wanted issues

- renovate.json
see https://github.com/renovatebot/renovate/discussions/13213
> chore(renovate): Fix autoclosed PRs

- readme.md
and improve license badge/link
> docs(readme): Add snyk package health badge

- .npmrc
- auto-changelog.hbs
- changelog-has-version.sh
- docs/RELEASE.md
- package-lock.json
- package.json
Since I was having a hard time remembering all the steps we did previously I wanted to document them. So I did that while doing the 0.8.0 release.
I also decided to add the tools that we are using for this to the devDependencies, to speed up things and pin the versions/make them transparent.
After describing all the release steps I discovered that this would also be a good place to describe how the project currently prioritizes issues and PRs.
> chore: Describe release/publish steps

- SECURITY.md
- package.json
Inspired by the following sources:
- https://snyk.io/blog/ten-git-hub-security-best-practices/
- https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md
- https://expressjs.com/en/resources/contributing.html#security-policies-and-procedures
- https://docs.github.com/en/code-security/security-advisories/about-coordinated-disclosure-of-security-vulnerabilities
> docs: Add security policy

- lib/sax.js
- test/parse/__snapshots__/entities.test.js.snap
- test/parse/entities.test.js
> fix(sax): Only use own properties in entityMap

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
for bug reports and feature requests, this way the security policy is one option to follow when trying to create an issue
> docs: Add issue templates

- .github/workflows/codeql.yml
- test/xss.test.js
Related PR #416 
Docs: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning
> ci: Add CodeQL scan

- lib/.eslintrc.yml
- package-lock.json
- package.json
> chore: Add eslint-plugin-node for `lib`

- lib/sax.js
I always wondered what this said.
> style: Translate/drop non English comments

- .github/workflows/test-node.js.yml
- codecov.yml
- jest.config.js
- readme.md
using https://codecov.io
After landing this PR the reference coverage is available under https://app.codecov.io/gh/xmldom/xmldom and shown as a badge in the readme.
> ci: check test coverage in PRs

- readme.md
###PULL REQUEST TITLE
Appropriately Semicolon Use
###ISSUE
Not use semicolon
###CHANGES
added semicolon after docs and past word
###SOLUTION
added semicolon
I hope you look out into this and consider my contribution.
> docs: add missing commas to readme

- lib/dom.js
- package-lock.json
- test/dom/named-node-map.test.js
- test/dom/node-list.test.js
> feat: add iterator function to NodeList and NamedNodeMap

- CHANGELOG.md
- docs/RELEASE.md
- package.json
fixes #686
https://dev.to/karfau/release-090-of-xmldomxmldom-4106
> docs: prepare 0.9.0

- test/parse/file-bom.xml
- test/parse/file.test.js
https://github.com/xmldom/xmldom/issues/753
> test: verify BOM handling

- lib/dom.js
- test/dom/document.test.js
- test/dom/element.test.js
to resolve a regression introduced in #760
fixes #763
> fix: re-index childNodes on insertBefore

- lib/dom.js
- test/dom/element.test.js
PR contributes the implementaton of the [Level2 Core function `hasAttributes`](https://www.w3.org/TR/DOM-Level-2-Core/#core-ID-NodeHasAttrs).
* Adds basic implementation in `dom.js`
* Adds a set of tests in `element.test.js`
> Implementation of `hasAttributes`

- lib/dom.js
- test/dom/element.test.js
> fix: [0.8.x] update `ownerDocument` when moving nodes between documents
